# Making changes? https://github.com/nektos/act may help you test locally

name: Build with GitHub Actions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: OreStaging
    steps:
      # Setup
      - name: Check out
        uses: actions/checkout@v2
      - name: "Setup JDK 16"
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "16"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Actually build
      - name: Build with Gradle
        run: ./gradlew build
        env:
          MINOR_VERSION: ${{ github.run_number }}
          PATCH_VERSION: ${{ github.run_attempt }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/libs/sponge-plugin-template-*.jar
          if-no-files-found: error
      - name: Upload to Ore
        uses: dualspiral/ore-upload-action@0.0.1
        with:
          plugin: plugin
          description: "Test description"
          apiKey: ${{ secrets.ORE_KEY }}
          tag: Release
          projectId: "test-plugin"
          oreUrl: "https://staging-ore.spongepowered.org/"
          createForumPost: false
      - name: Archive test results
        if: "${{ always() }}"
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            build/reports/